added docker configuration and typeORM connection setup
mmarganski/message-chat-nest-api pull request #2
Opened 2021-08-03 10:02 UTC by mmarganski

2021-08-03 12:54 UTC, jpudysz requested changes

2021-08-03 12:54 UTC, jpudysz commented on docker-compose.yml
> +      - 8081:8080
enter, this sign means new line

2021-08-03 12:54 UTC, jpudysz commented on Dockerfile
> +CMD ["node", "dist/main"]
enter, this sign means new line

2021-08-03 12:54 UTC, jpudysz commented on src/app.service.ts
> +import { User } from './entity/User'
this is bad import, add `index.ts`

2021-08-03 12:54 UTC, jpudysz commented on src/app.service.ts
> +export const testDBConnection = async () => {
no console longs inside PR

2021-08-03 12:54 UTC, jpudysz commented on src/app.service.ts
> +export const test = async () => {
same here, I think that this code shouldn't be included into PR

2021-08-03 12:54 UTC, jpudysz commented on src/app.service.ts
> +}
nl

2021-08-03 12:54 UTC, jpudysz commented on src/main.ts
> +import "reflect-metadata"
import order

2021-08-03 12:54 UTC, jpudysz commented on src/main.ts
> +test()
nl

2021-08-03 13:08 UTC, WadasGrzegorz requested changes

2021-08-03 13:08 UTC, WadasGrzegorz commented on Dockerfile
> +RUN yarn install --production=false
you can omit ```--production=false``` in this place

2021-08-03 13:08 UTC, WadasGrzegorz commented on Dockerfile
> +RUN npm run build
use yarn instead

2021-08-03 13:08 UTC, WadasGrzegorz commented on Dockerfile
> +EXPOSE 3002
remove it - development is only for build

2021-08-03 13:08 UTC, WadasGrzegorz commented on Dockerfile
> +CMD ["node", "dist/main"]
nl

2021-08-03 13:08 UTC, WadasGrzegorz commented on docker-compose.yml
> +      - 8081:8080
nl

2021-08-03 13:08 UTC, WadasGrzegorz commented on ormconfig.json
> +}
nl

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/app.service.ts
> +import { User } from './entity/User'
entity should have index

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/app.service.ts
> +}
nl

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/app.service.ts
> +
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/User.ts
> +}
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/main.ts
> +test()
remove it

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/main.ts
> +import "reflect-metadata"
?

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/main.ts
> +import { testDBConnection, test } from './app.service'
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/User.ts
> +
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/User.ts
> +  @PrimaryColumn()
You can use `PrimaryGeneratedColumn` instead

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/User.ts
> +  userId: string
Id should be number

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/Room.ts
> +
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/Message.ts
> +}
.

2021-08-03 13:08 UTC, WadasGrzegorz commented on src/entity/Message.ts
> +
.

2021-08-04 08:58 UTC, jpudysz requested changes

2021-08-04 08:58 UTC, jpudysz commented on src/app.controller.ts
> +// import { AppService } from './app.service'
dont push commented code

2021-08-04 08:58 UTC, jpudysz commented on src/entity/Message.ts
> +import { User, Room } from './index'
dont import from index, you can import from file if you are in the same folder

2021-08-04 08:58 UTC, jpudysz commented on src/entity/Room.ts
> +import { User, Message } from './index'
aa

2021-08-04 08:58 UTC, jpudysz commented on src/entity/User.ts
> +import { Message } from './index'
aa

2021-08-04 11:46 UTC, jpudysz requested changes

2021-08-04 11:46 UTC, jpudysz commented on package.json
> +    "@nestjs/typeorm": "^8.0.2",
.

2021-08-04 11:46 UTC, jpudysz commented on src/lib/entities/Message.entity.ts
> +import { RoomEntity } from './'
.

2021-08-04 11:46 UTC, jpudysz commented on src/lib/entities/Room.entity.ts
> +import { MessageEntity } from './'
not like that, use `'./MessageEntity'`

2021-08-04 11:46 UTC, jpudysz commented on src/main.ts
> +import { AppModule } from './modules/app/app.module'
bad, nested import, use index.ts

2021-08-04 11:46 UTC, jpudysz commented on src/modules/app/app.module.ts
> +import { Connection, getConnectionOptions } from 'typeorm'
import order

2021-08-04 11:46 UTC, jpudysz commented on src/modules/app/app.module.ts
> +import { MessageEntity, RoomEntity, UserEntity } from '../../lib/entities'
bad import

2021-08-04 11:46 UTC, jpudysz commented on src/modules/app/app.service.ts
> +import { InjectRepository } from '@nestjs/typeorm'
import order

2021-08-04 12:41 UTC, jpudysz requested changes

2021-08-04 12:41 UTC, jpudysz commented on src/lib/entities/index.ts
> +export { UserRoomEntity } from './UserRoom.entity'
nl

2021-08-04 12:41 UTC, jpudysz commented on src/modules/app/app.module.ts
> +import { MessageEntity, RoomEntity, UserEntity } from 'lib/entities'
import order

2021-08-04 13:01 UTC, WadasGrzegorz requested changes

2021-08-04 13:01 UTC, WadasGrzegorz commented on ormconfig.json
> +{
this file shouldn't be in GitHub - what if you had there production config ?

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/Message.entity.ts
> +
rm empty line

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/Message.entity.ts
> +import { RoomEntity } from './Room.entity'
file name should starts with lowercase

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/Message.entity.ts
> +@Entity({name: 'Message'})
table name should start with lowercase and spaces around

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/Room.entity.ts
> +@Entity({name: 'Room'})
whole file aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/User.entity.ts
> +import { Column, Entity, PrimaryColumn } from 'typeorm'
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/UserRoom.entity.ts
> +import { Column, Entity, PrimaryGeneratedColumn, Unique } from 'typeorm'
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/lib/entities/index.ts
> +export { UserRoomEntity } from './UserRoom.entity'
nl

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.module.ts
> +    constructor(private readonly connection: Connection) {}
?

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        private readonly connection: Connection,
rm

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        return this.roomRepository.find({select: ['roomName'], where: {isPrivate: false}})
spaces

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +    async getUsersByRoomName (roomName: string) {
just ```
         return this.roomRepository.find({ where: { roomName } })```

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const [user] = await userRepository.find({where: { socketId}})
aa and you can use findOne

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const [room] = await roomRepository.find({where: {roomName}})
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const userRepository = this.userRepository
```  
 return this.userRepository.save({
             socketId,
             userName,
             avatar,
             isActive: true
         })
```

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const roomRepository = this.roomRepository
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const messageRepository = this.messageRepository
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        // room.users = [...room.users, user]
.

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +        const [user] = await userRepository.find({where: {socketId}})
aa

2021-08-04 13:01 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +
in this place you can use update where instead two queries you make only one

2021-08-04 13:45 UTC, WadasGrzegorz requested changes

2021-08-04 13:45 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +    async getUsersList() {
you don't need `async` if you not using `await`

2021-08-04 13:45 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +    async getRoomNames() {
aa

2021-08-04 13:45 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +
. :)

2021-08-04 13:45 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +
aa

2021-08-04 13:55 UTC, WadasGrzegorz requested changes

2021-08-04 13:55 UTC, WadasGrzegorz commented on src/lib/entities/index.ts
> +export { UserRoomEntity } from './userRoom.entity'
it is work ?

2021-08-04 13:55 UTC, WadasGrzegorz commented on src/modules/app/app.service.ts
> +
remove empty line after return

2021-08-04 14:26 UTC, WadasGrzegorz approved these changes

2021-08-05 07:03 UTC, merged